compile: driver.cpp vehicle.cpp car.cpp truck.cpp dealership.cpp
	g++ -Wall -o dealership driver.cpp vehicle.cpp car.cpp truck.cpp dealership.cpp
run: compile
	./dealership dealer.txt
clean:
	rm dealership
